### ISSUE TITLE
Use Minio as Azure storage gateway

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod-microsoft-aks-guide#1]
As Azure storage is not S3 compatible, Minio will need to be configured as a gateway for Azure storage

See [Minio gateway for Azure](https://docs.min.io/docs/minio-gateway-for-azure.html)

**Comment by chaonengs** [comment]
The latest Minio removed azure gateway

**Comment by MrSimonEmms** [comment]
This is solved in https://github.com/gitpod-io/gitpod/pull/10717
