### ISSUE TITLE
https-certifcates is not ready state, even after deleting the cert-manager pods

### ISSUE THREAD

**Issue by sai-synergy-user** [gitpod-io/gitpod-microsoft-aks-guide#13]
Hi,

Even after performing the kubectl delete pods -n cert-manager --all
pod "cert-manager-57c6799586-nzbr4" deleted
pod "cert-manager-cainjector-7d55bf8f78-hb7zl" deleted
pod "cert-manager-webhook-577f77586f-hxjmz" deleted
kubectl get certificate
NAME                           READY   SECRET                         AGE
builtin-registry-facade-cert   True    builtin-registry-facade-cert   77m
ca-issuer-ca                   True    ca-issuer-ca                   77m
https-certificates             False   https-certificates             81m
ws-daemon-tls                  True    ws-daemon-tls                  77m
ws-manager                     True    ws-manager-client-tls          77m
ws-manager-tls                 True    ws-manager-tls                 77m

https-certificates are not ready, I have verified the dns-zone names server they are properly configured, Please let know if some thing else need to be performed. Validated the principal identity information. everything is correctly configured, but still the https-certificates are not ready

**Comment by MrSimonEmms** [comment]
Have you set up your nameserver correctly, as per https://github.com/gitpod-io/gitpod-microsoft-aks-guide/issues/9#issuecomment-1038863293?
