### ISSUE TITLE
DNS question

### ISSUE THREAD

**Issue by behrica** [gitpod-io/gitpod-microsoft-aks-guide#9]
### Bug description

I came to the  issue mentioned as 
`The most likely reason is because the DNS01 challenge has yet to resolve. If using SETUP_MANAGED_DNS, you will need to update your DNS records to point to the Azure DNS zone nameserver.`

Is is possible to add more documentation, what need to be done on teh DNS level, before teh `make install` can be run.

`Which` DNS record need to be updated to oint to the Azure DNS zone nameserve (which is ?)
and how this relates to the config setting of:

# Base domain
DOMAIN=

### Steps to reproduce

make install

**Comment by neilkuantm** [comment]
I did not understand  about this, probably is this

https://github.com/gitpod-io/gitpod-microsoft-aks-guide/blob/2f2b8c9f2e17437fb1c519e4c1c732078c0f0d39/setup.sh#L173
 ?
 
 cc @MrSimonEmms  , please help~

**Comment by MrSimonEmms** [comment]
Yes, the documentation is probably doesn't explain the process very well. So, here goes...

Let's say you have the domain `example.com` and want to run Gitpod on `gitpod.example.com`. You have this domain managed by a domain registrar (I'm going to use Cloudflare as the example, but it could be anything).

You run this guide and set `SETUP_MANAGED_DNS` to `true`. What this does is create an [Azure DNS zone](https://docs.microsoft.com/en-us/azure/dns/dns-zones-records) for `gitpod.example.com`. When you look in your Azure portal for this DNS zone, you'll see something like this:

![image](https://user-images.githubusercontent.com/275848/153837385-42ef4521-ed1c-49fd-bc89-3350da548265.png)

You now need to point `example.com` to this Azure DNS zone. To do this, go to the Cloudflare control panel for `example.com` and create a nameserver record. Set the name to `gitpod` and the value to whatever the nameserver values are generated by Azure - in our example, these are `ns1-35.azure-dns.com`, `ns2-35.azure-dns.net`, `ns3-35.azure-dns.org` and `ns4-35.azure-dns.info`. It's worth adding all them to provide maximum redundancy/resillience.

![image](https://user-images.githubusercontent.com/275848/153837842-fa57aa18-1019-4e67-85b1-4238e2ca9365.png)

When you click save and (after a few minutes to allow for propagation), any traffic sent to `gitpod.example.com` will be forwarded to the Azure DNS zone for resolution
